### ISSUE TITLE
Errors

### ISSUE THREAD

**Issue by sergeydi** [andrewwoz/StreamReader.swift#1]
Hi,
I got this errors using swift3 on ubuntu 14.04:

user@pc444:~/filterit$ swift newStreamReader.swift 
newStreamReader.swift:36:30: error: cannot convert value of type 'Data' to type 'NSData!' in coercion
            self.delimData = delimData as NSData!
                             ^~~~~~~~~
newStreamReader.swift:61:47: error: cannot convert value of type 'NSMutableData!' to type 'Data' in coercion
                    let line = NSString(data: buffer as Data, encoding: encoding.rawValue);
                                              ^~~~~~
newStreamReader.swift:78:16: error: cannot convert value of type 'NSString?' to type 'String?' in coercion
        return line as String?
               ^~~~
newStreamReader.swift:113:24: warning: result of call to 'seekToEndOfFile()' is unused
            fileHandle.seekToEndOfFile()

Could you please help to fi this?

**Comment by andrewwoz** [comment]
This class isn't written for Ubuntu because it uses foundation classes (prefix NS). I'm going to add Ubuntu support soon (today or tomorrow morning). Thanks for feedback.

**Comment by andrewwoz** [comment]
I've added ubuntu support.

**Comment by sergeydi** [comment]
Thank you so much.

**Comment by sergeydi** [comment]
Also this code has memory leak. On macOS it is fixed by autoreleasepool. But Ubuntu do not has this feature. Do you have any ideas how to fix this on Ubuntu?

**Comment by andrewwoz** [comment]
Hmm ... you can use this class from [this page](https://marc.ttias.be/swift-users/2016-11/msg00039.php) to fix this issue on ubuntu. 

``` swift
internal class NSAutoreleasePool {
    fileprivate static var _current = NSThreadSpecific<NSAutoreleasePool>()
    internal static var current: NSAutoreleasePool {
        return _current.get() {
            return NSAutoreleasePool()
        }
    }
    
    var depth: Int = 0
    var objects = [[AnyObject]]()
    
    fileprivate override init() { }
    
    fileprivate func push() {
        objects.append([AnyObject]())
        depth += 1
    }
    
    fileprivate func pop() {
        objects.removeLast()
        depth -= 1
    }
    
    func add(_ object: AnyObject) {
        objects[depth - 1].append(object)
    }
}

public func autoreleasepool(_ code: () -> ()) {
    NSAutoreleasePool.current.push()
    code()
    NSAutoreleasePool.current.pop()
}
```

But i'm not sure, because I'm not using swift on  ubuntu.
Let me know when you fix this.

**Comment by sergeydi** [comment]
Thank you. I will try this tomorrow and write feedback.

**Comment by sergeydi** [comment]
I try "internal class NSAutoreleasePool {..." and got:
 error: use of unresolved identifier 'NSThreadSpecific'
    fileprivate static var _current = NSThreadSpecific<NSAutoreleasePool>()

**Comment by andrewwoz** [comment]
I don't found anything about this problem on ubuntu. Are you sure that memory leak takes place in this code?

**Comment by andrewwoz** [comment]
Maybe swift for ubuntu has something like garbage collector or something similar. Sorry can't help you with this kind of problem ... :(

**Comment by sergeydi** [comment]
In any case, thank you :)

**Comment by sergeydi** [comment]
I found the problem, memory leaked using this line:
let tmpData = fileHandle.readData(ofLength: chunkSize)

**Comment by andrewwoz** [comment]
What tool are you using to find those leaks?. Because I can't find any leaks in this code on mac os x

**Comment by andrewwoz** [comment]
Please file new issue about memory leaks on ubuntu and provide more info (screens)

**Comment by andrewwoz** [comment]
<img width="1284" alt="screen shot 2016-11-28 at 5 12 48 pm" src="https://cloud.githubusercontent.com/assets/6348345/20673535/2053c590-b58e-11e6-8fb7-6ba5b3792276.png">

**Comment by sergeydi** [comment]
I create large(10GB) file.txt with a lot of lines (~20.000.000). After that I use this code (attached)
[readIt.txt](https://github.com/andrewwoz/StreamReader.swift/files/616711/readIt.txt)
When I execute this code, I takes about 5-10 sec that my 8GB RAM becomes empty.
