### ISSUE TITLE
Memory leak

### ISSUE THREAD

**Issue by sergeydi** [andrewwoz/StreamReader.swift#2]
I create large(10GB) file.txt with a lot of lines (~20.000.000). After that I use this code (attached)
[readIt.txt](https://github.com/andrewwoz/StreamReader.swift/files/616788/readIt.txt)
When I execute this code, I takes about 5-10 sec that my 8GB RAM becomes empty.

Ubuntu 14.04, Swift 3.0.1

**Comment by andrewwoz** [comment]
Thanks, I'm trying to fix this issue right now.

**Comment by andrewwoz** [comment]
I'm tested this class with text file(20m lines). Works good. Memory footprint - 1.5 MB (on os x). Memory leaks not detected. 
Please test it on ubuntu and let me know about result

**Comment by sergeydi** [comment]
Works perfect. Thank you.

**Comment by andrewwoz** [comment]
You're welcome. :)
