### ISSUE TITLE
Read each line in multithreading

### ISSUE THREAD

**Issue by sergeydi** [andrewwoz/StreamReader.swift#3]
Could you please help me, I read from txt file about 200GB and it takes about 8 hours to do all I need with each line. But my server has 6 hardware cores. How can I read each line in 6 threads?
Thank you.

**Comment by andrewwoz** [comment]
You can read file from 1 thread , it's faster than reading 1 file from 6 threads - see [here](http://stackoverflow.com/a/10625178). And you can process read line in parallel thread. 
Pseudo code:
```swift
for line in reader {
    parallel.run {
        process(line)
    }
}
```

**Comment by andrewwoz** [comment]
Or you can split your file in 6 parts and process each part on separate thread.

**Comment by sergeydi** [comment]
> parallel.run {

How to do this in Swiff (something based on GCD)?

> Or you can split your file in 6 parts and process each part on separate thread.

The same way as in the link?

**Comment by andrewwoz** [comment]
> How to do this in Swiff (something based on GCD)?

yes GCD it great tool for multithreading.

> The same way as in the link?

This [answer](http://stackoverflow.com/a/10625178) uses array (you can't put content of your file into array - it's too huge), but in your case this is raw file. So you can create 6 files from 1. Or you can specify range of bytes for each process. For example 0..<33 GB for 1 core(process), 33 GB..<66 GB for second code(process), ...

Let me know if you have troubles with implementing this in code.

**Comment by sergeydi** [comment]
Thank you so much.

**Comment by andrewwoz** [comment]
You're welcome!
In my opinion, first way is better than second.
> You can read file from 1 thread , it's faster than reading 1 file from 6 threads - see here. And you can process read line in parallel thread.

**Comment by sergeydi** [comment]
GCD for linux is still in development process. Any ideas how to read line in parallel thread without GCD?

**Comment by andrewwoz** [comment]
I don't know any library like `libdispatch` (GCD) on Ubuntu. 
Sorry can't help here. But you can try to use native libs.

**Comment by sergeydi** [comment]
I found solution:

    let reader = LineReader(path: pathToFile)
    var threads = [Thread]()

    func readTxtFile() {
       while  let line = reader?.nextLine {
         autoreleasepool {
           // To do with each line
       }}
    }

    for threadNumber in 0...threadsCount-1 {
       threads.append(Thread(){ readTxtFile() })
       threads[threadNumber].start()    
    }

select(0, nil, nil, nil, nil)

**Comment by andrewwoz** [comment]
It's great!! Does it work much faster? Is Thread custom class or lib?

**Comment by sergeydi** [comment]
**1)** 1GB file:
1 thread   - 2:35 min
2 threads - 1:21 min
number of threads must be not more then number of cores. If your CPU has 2 cores and 4 threads, use 2 threads in the code.
**2)** https://developer.apple.com/reference/foundation/thread
It works on Ubuntu!!!

**Comment by andrewwoz** [comment]
Oh amazing, Thanks for feedback. Your activity on this repo was very important for me. 
Good luck in your project!

**Comment by sergeydi** [comment]
Thanks you :)
