### ISSUE TITLE
read each new line from text file

### ISSUE THREAD

**Issue by sergeydi** [andrewwoz/StreamReader.swift#4]
Hi,
I have a log file and I need to read each new line from this file. If new line added to this file, I need to detect this moment and read this line, or check every n seconds and read all new lines added to log file during this N seconds
May be you have any ideas hot to do this?

**Comment by andrewwoz** [comment]
Hello, It's easy. Just monitor your log file for changes (you can use this [framework](https://github.com/Eonil/FileSystemEvents)). And when append(write) event occurs just read new lines from pervious **offset** to the end of file (after read completed save current file **offset**). 
Happy coding 😃

**Comment by sergeydi** [comment]
Thank you.
